### PR TITLE
Changed "a.remove()" to "display: none"

### PR DESCRIPTION
**Pull request by chongtzezhao**

### CODE REVIEW

**Comment by michaelsanford** [comment]
Hi there @thepoppycat !

Thanks for your PR. Have you had a look at the [contributor guidelines](https://github.com/michaelsanford/desocialize-media/blob/main/CONTRIBUTING.md)?

As a maintainer, one of _my_ goals in participating in Hacktoberfest is to promote (what I see as) good open source coding practices, _as well as_ providing new- and intermediary-level developers with an opportunity to experience contributing to a project, as "small" as that contribution may be in terms of code.

One of those practices, and part of the experience, is to follow the flow of a ticket from start to finish. That's trivial working in a tiny repo like this one, but in a larger project, it's _absolutely mandatory_ and not doing so makes projects unmanageable for the maintainer.

That usually means claiming a ticket, writing code, testing it locally, and then submitting a PR _that references that ticket in the commit message_. Those steps are outlined in ["Submitting Pull Requests"](https://github.com/michaelsanford/desocialize-media/blob/main/CONTRIBUTING.md#submitting-pull-requests).

So, would you please:

1. Comment on #2 saying you'll do it,
1. [_Rebase_ your branch and edit the commit message](https://stackoverflow.com/a/8981216/114900) to something like `Changed "a.remove()" to "display: none". Fixes #2`, which is a [Github linking word](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) that will automatically close the ticket when the PR is merged.
1. Force push your own branch, which will automatically update the PR.

If you need help rebasing your branch, comment here and I'll be happy to help.

Thanks 😄

**Comment by michaelsanford** [comment]
Furthermore, with respect, I doubt that this has been tested as the commit was made directly in the Github UI (the commit is cryptographically signed with the web editor GPG key).

Please see [CONTRIBUTING.md#testing-your-work](CONTRIBUTING.md#testing-your-work).

Right now, it feels like a drive-by low-effort PR. In good-faith I'll offer the benefit of the doubt to allow a couple of days to address the issues above.

Thanks.

**Comment by chongtzezhao** [comment]
Apologies, how can I rebase the branch if I don't have a local clone of the repository. Do I just create one and continue from there?

**Comment by michaelsanford** [comment]
@thepoppycat  Glad you asked! This is part of the learning OSS experience.

I see you [already have a fork](https://github.com/thepoppycat/desocialize-media), so just clone it locally, and then add this repo as the "upstream":

```
git@github.com:thepoppycat/desocialize-media.git
cd desocialize-media
git remote add upstream git@github.com:michaelsanford/desocialize-media.git
```

Now you have a local copy of your work. If you look at the log, you'll see your commit at the top:

```
git log

commit adb5889fb214045831cd9b66d8ac0518ecb58fb0 (HEAD -> main, origin/main, origin/HEAD)
Author: thepoppycat <47619363+thepoppycat@users.noreply.github.com>
Date:   Thu Oct 8 09:56:37 2020 +0800

    Changed "a.remove()" to "display: none".
```

And now all you have to do is rebase your last commit's message.

Luckily, there is a shortcut _to just edit the commit message of your last commit_, which does a bunch of things for you, and uses `git commit` (instead of `git rebase`):

```
git commit --edit --ammend
```

This will open a command window, possibly in the `vi` editor:

```
Changed "a.remove()" to "display: none"

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Author:    thepoppycat <47619363+thepoppycat@users.noreply.github.com>
# Date:      Thu Oct 8 09:56:37 2020 +0800
#
# On branch main
# Your branch is up to date with 'origin/main'.
#
# Changes to be committed:
#       modified:   desocialize.js
#
~  
~  
~  
```

It it looks like this, you need to enter Append mode by pressing `a` on the keyboard, moving the cursor to the start of end of the existing message and typing in the extra part, changing it to something like this:

```
Changed "a.remove()" to "display: none". Fixes #2 

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Author:    thepoppycat <47619363+thepoppycat@users.noreply.github.com>
# Date:      Thu Oct 8 09:56:37 2020 +0800
#
# On branch main
# Your branch is up to date with 'origin/main'.
#
# Changes to be committed:
#       modified:   desocialize.js
#
~  
~  
~
```

Now, to quit and save your changes, press `escape` followed by this exact command `:wq` , which you will see being typed at the bottom of the window (it's not a key combination, you type each individually, it means "command mode, *w*rite, *q*uit"). Hit enter, and you should something like this:

```
[main 4b06fc2] Changed "a.remove()" to "display: none". Fixes #2
 Author: thepoppycat <47619363+thepoppycat@users.noreply.github.com>
 Date: Thu Oct 8 09:56:37 2020 +0800
 1 file changed, 4 insertions(+), 4 deletions(-)

C:\poppy [main ↓1 ↑1]>
```

Now all you have to do is force push your main branch:

```
git push --force-with-lease
```

Let me know if you have other questions.

**Comment by michaelsanford** [comment]
Now you can test the extension in Chrome, like this: https://webkul.com/blog/how-to-install-the-unpacked-extension-in-chrome/ 

The code will work the same in Chrome and Firefox, so testing in only one is fine. If you have Firefox, you can test in that instead. It's fine.

**Pull request closed without merging**
